serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12345
  path: /api/gateway

loggerConfig:
  outputDir: ./logs/
  outputFile: gateway.log

databaseConfig:
  dbUsername: username
  dbPassword: password
  dbHostname: hostname
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: dbname
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

threadConfig:
  numThreads: 10
  requestDelay: 5

idmConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12346
  path: /api/idm

idmEndpoints:
  register: /register
  login: /login
  session: /session
  privilege: /privilege

moviesConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12347
  path: /api/movies

moviesEndpoints:
  search: /search
  browse: /browse/
  get: /get/
  thumbnail: /thumbnail
  people: /people
  peopleSearch: /people/search
  peopleGet: /people/get/
  
billingConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12348
  path: /api/billing
  
billingEndpoints:
  cartInsert: /cart/insert
  cartUpdate: /cart/update
  cartDelete: /cart/delete
  cartRetrieve: /cart/retrieve
  cartClear: /cart/clear
  orderPlace: /order/place
  orderRetrieve: /order/retrieve
  



